old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            vhost: '%env(RABBITMQ_VHOST)%'
            lazy: false
            connection_timeout: 2
            read_write_timeout: 2
            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false
            # requires php-amqplib v2.4.1+
            heartbeat: 0
            use_socket: false # default false
    consumers:
        mails_queue: &consumer_mails_queue
            connection: default
            exchange_options: {name: 'mails_queue', type: direct}
            queue_options: {name: 'mails_queue'}
            callback: '%mailer.consumer.class%'
