# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    working_directory: ~/repo

    steps:
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install bcmath

      - run:
          name: Install Memcached
          command: sudo apt-get update && sudo apt-get install -y libz-dev libmemcached-dev

      - run:
          name: Install PHP Memached extension
          command: sudo pecl install memcached

      - run:
          name: Enable PHP Memached extension
          command: sudo echo extension=memcached.so >> /usr/local/etc/php/conf.d/memcached.ini

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: php bin/phpunit
